# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06476ca468dba2c57a0d56c8ac7adaa9318aa3108885aaf8db2ab2540df7e00db1c4ba712fbe34d309d521be9a37ca4408d29ca4833e7d3bbe892beac673569f

test:
  secret_key_base: 9dde5cefb44d6c5605a7d14cbc5b186c82758680bf512a93a01a9d3de7d25168efff649158334bd0c7c14d3c04f8e7cdd0207bd585da573179f9585159aaf183

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
